name: Push to Space
on: [push, workflow_dispatch]

jobs:
    push-to-space:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Deta Space Deployment Github Action
          uses: neobrains/space-deployment-github-action@latest
          with:
            access_token: ${{ secrets.SPACE_ACCESS_TOKEN }}
            project_id: ${{ secrets.SPACE_PROJECT_ID }}
            space_push: true
            space_release: true
            list_on_discovery: true
